name: ecommerce
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  intl: ^0.19.0
  logger: ^2.2.0
  url_launcher: ^6.2.5
  flutter_native_splash: ^2.4.7

  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_storage: ^2.1.1
  smooth_page_indicator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:

  assets:
    - assets/logo/
    - assets/images/
    - assets/icons/brands/
    - assets/images/profile/
    - assets/images/dashboard/
    - assets/images/splash_images/
    - assets/images/welcome_images/
    - assets/images/forget_password/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/banners/
    - assets/icons/payment_methods/
    - assets/images/products/
    - assets/images/brands/
    - assets/icons/categories/
    - assets/icons/payment_methods/paypal.png
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic

  uses-material-design: true

